DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS orderitem;
DROP TABLE IF EXISTS [order];
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS publisher;
DROP TABLE IF EXISTS author;